Repository wecode-bootcamp-korea/29-2nd-MyJejuStay-frontend, pull requests merged in 2022-02, with the labels that each got.

#7 [29기 석정도] 전역폰트 설정
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#4 [29기 정수진] SignUp
  src/Router.js
  src/pages/SignUp/FormLayout.js
  src/pages/SignUp/Input.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUpForm.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#8 [29기 김지윤] Add: Footer 레이아웃 완성
  .gitattributes
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/FooterData.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#10 [29기 김지윤] Nav 레이아웃 구현
  public/index.html
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Theme.js
  src/components/Nav/UserInfo.js
  src/pages/SignUp/SignUpForm.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#12 [29기 석정도] conflict 해결
  public/data/accommodations.json
  src/pages/ProductList/ProductItem/ProductItemContent/ProductImgSlider.js
  src/pages/ProductList/ProductItem/ProductItemContent/ProductItemInfo.js
Labels: Status: 리뷰 요청

#13 [29기 김지윤] Add: Main페이지
  public/data/Review/Review.json
  public/images/Main/stay2.jpg
  src/pages/Main/Main.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#16 [29기 김지윤] Modify: 링크 변경
  src/components/Nav/Theme.js
Labels: Status: 리뷰 요청

#11 [29기 석정도] 숙소 필터링
  package-lock.json
  package.json
  public/data/accommodations.json
  public/index.html
  src/Router.js
  src/api/config.js
  src/components/Nav/Nav.js
  src/pages/ProductList/ProductItem/ProductItemContent/ProductImgSlider.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductListFilter/DateRangeFilter.js
  src/pages/ProductList/ProductListFilter/FilterModal.js
  src/pages/ProductList/ProductListFilter/FilterSort.js
  src/pages/ProductList/ProductListFilter/ProductListFilter.js
  src/pages/ProductList/ProductListFilter/Toggle.js
Labels: Status: 리뷰 요청

#15 [29기 김지윤] Main CSS 변경
  src/Router.js
  src/api/config.js
  src/pages/Main/Main.js
  src/pages/MyPage/MyPage.js
Labels: Status: 리뷰 요청

#21 Add: 마이페이지
  src/Router.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPageCancel.js
  src/pages/MyPage/MyPageCoupon.js
  src/pages/MyPage/MyPageData.js
  src/pages/MyPage/MyPageDetail.js
  src/pages/MyPage/MyPageLike.js
  src/pages/MyPage/MyPagePast.js
  src/pages/MyPage/MyPageReservation.js
  src/pages/MyPage/MyPageSubMenu.js
Labels: Status: 리뷰 요청

#9 [29기 임채현] 상세페이지 숙소 정보
  package-lock.json
  package.json
  public/data/DetailPage/DetailPageHeader/DetailPage_Accommodations_Data.json
  src/Router.js
  src/api/config.js
  src/pages/DetailPage/DetailPageInfo/DetailPageInfo.js
  src/pages/DetailPage/DetailPageInfo/DetailPageInfoCheckInOut.js
  src/pages/Main/Main.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#20 [29기 임채현] 상세페이지 사진 컴포넌트
  public/data/DetailPage/DetailPageHeader/DetailPage_Accommodations_Data.json
  src/Router.js
  src/pages/DetailPage/DetailPagePhoto/DetailPagePhoto.js
Labels: Status: 리뷰 요청

#19 [29기 임채현] 상세페이지 예약 컴포넌트
  package-lock.json
  package.json
  public/data/DetailPage/DetailPageHeader/DetailPage_Accommodations_Data.json
  public/data/DetailPage/DetailPageHeader/DetailPage_Reviews_Images.json
  public/index.html
  src/Router.js
  src/pages/DetailPage/DetailPageReservation/DetailPageReservation.js
  src/pages/DetailPage/DetailPageReservation/DetailPageReservationCheckInOut.js
  src/pages/DetailPage/DetailPageReservation/DetailPageReservationPersonnel.js
  src/pages/DetailPage/DetailPageReservation/Reservation.js
  src/pages/DetailPage/DetailPageReservation/ReservationContent/ReservationContent.js
  src/pages/DetailPage/DetailPageReservation/ReservationContent/ReservationHostMessage.js
  src/pages/DetailPage/DetailPageReservation/ReservationContent/ReservationMessage.js
  src/pages/DetailPage/DetailPageReservation/ReservationHeader.js
  src/pages/DetailPage/DetailPageReservation/ReservationPersonnelModal/ReservationPersonnelModal.js
  src/pages/DetailPage/DetailPageReservation/ReservationPersonnelModal/ReservationPersonnelModalRow.js
  src/pages/DetailPage/DetailPageReservation/ReservationPrice.js
  src/pages/ProductList/ProductListFilter/DateRangeFilter.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#14 [29기 정수진] 카카오 소셜 로그인
  .gitignore
  package-lock.json
  package.json
  src/Router.js
  src/api/config.js
  src/pages/KaKao/App.js
  src/pages/KaKao/Auth.js
Labels: Status: 추가 기능 구현중, Status: 수정 요청

#23 [29기 임채현] 상세페이지 프로토타입
  package-lock.json
  package.json
  public/data/DetailPage/DetailPageHeader/DetailPage_Accommodations_Data.json
  src/Router.js
  src/pages/DetailPage/DetailPage.js
  src/pages/DetailPage/DetailPageHeader/DetailPageHeader.js
  src/pages/DetailPage/DetailPageInfo/DetailPageInfo.js
  src/pages/DetailPage/DetailPageInfo/DetailPageInfoCheckInOut.js
  src/pages/DetailPage/DetailPagePhoto/DetailPagePhoto.js
  src/pages/DetailPage/DetailPageReservation/Reservation.js
Labels: Status: 리뷰 요청

#22 [29기 김지윤] 리뷰 페이지 구현
  public/data/Review/Review_Data.json
  public/images/bluesky.png
  src/Router.js
  src/api/config.js
  src/pages/Review/OneReview.js
  src/pages/Review/Review.js
  src/pages/Review/ReviewFilterData.js
  src/pages/Review/ReviewList.js
  src/pages/Review/ReviewLists.js
Labels: Status: 리뷰 요청

#24 이메일 로그인
  src/pages/Members/SignComponents/Button.js
  src/pages/Members/SignComponents/LoginForm.js
Labels: Status: Accepted

#17 [29기 석정도] kakao map api 작업
  public/images/productlist/marker.png
  public/index.html
  src/api/config.js
  src/components/Nav/Nav.js
  src/components/Nav/Theme.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductListFilter/FilterModal.js
  src/pages/ProductList/ProductListFilter/FilterSort.js
  src/pages/ProductList/ProductMap/MapContainer.js
  src/pages/ProductList/ProductMap/Overlay.css
Labels: Status: Accepted

#25 -예약가능여부 post 함수 작성
  src/pages/DetailPage/DetailPage.js
  src/pages/DetailPage/DetailPageHeader/DetailPageHeader.js
  src/pages/DetailPage/DetailPageInfo/DetailPageInfo.js
  src/pages/DetailPage/DetailPagePhoto/DetailPagePhoto.js
  src/pages/DetailPage/DetailPageReservation/DetailPageReservation.js
  src/pages/DetailPage/DetailPageReservation/DetailPageReservationCheckInOut.js
  src/pages/DetailPage/DetailPageReservation/DetailPageReservationPersonnel.js
  src/pages/DetailPage/DetailPageReservation/Reservation.js
  src/pages/DetailPage/DetailPageReservation/ReservationPrice.js
  src/pages/DetailPage/Review/OneReview.js
  src/pages/DetailPage/Review/Review.js
  src/pages/DetailPage/Review/ReviewFilterData.js
  src/pages/DetailPage/Review/ReviewList.js
  src/pages/DetailPage/Review/ReviewLists.js
Labels: Status: 리뷰 요청
